site:
  title: Easykube Documentation
  url: http://torloejborg.github.io/easykube
  start_page: easykube::index.adoc

urls:
  #html_extension_style: default
  html_extension_style: indexify

content:
  sources:
    - url: .
      branches: HEAD
      start_path: asciidoc
      worktrees: true

output:
  dir: ./docs
  clean: true

runtime:
  fetch: true

asciidoc:
  attributes:
    plantuml-format: svg
    source-highlighter: rouge
    linenums: true
    toc: left
    toclevels: 3
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: https://github.com/torloejborg/easykube-docs-ui/releases/download/v1.0.2/ui-bundle.zip
#    url: ../easykube-ui/build/ui-bundle.zip
    snapshot: true

antora:
  extensions:
  - require: "@springio/antora-extensions/asciinema-extension"
